version: "2.1"

services:
  fe:
    build: "${FE_REPO_PATH}"
    ports:
      - "80:80"
    links:
      - be
  be:
    build:
      context: "${BE_REPO_PATH}/Brainstorm"
      dockerfile: "${BE_REPO_PATH}/Brainstorm/Brainstorm.API/Dockerfile"
    ports:
      - "81:5000"
